name: release

on:
  push:
    tags:
      - 'v*'

defaults:
  run:
    shell: bash

jobs:
  compile-and-test:
    name: build and test ${{ matrix.build.target }} / ${{ matrix.build.ruby }}
    runs-on: ${{ matrix.build.os }}
    env:
      TARGET: ${{ matrix.build.target }}
    strategy:
      fail-fast: false
      matrix:
        build:
          - os: ubuntu-latest
            ruby: '3.2'
            target: x86_64-unknown-linux-gnu
            zig: false
            run-tests: true
            lib-file: lib/lib-ruby-parser/native/x86_64-unknown-linux-gnu/3.2/lib_ruby_parser.so

          - os: ubuntu-latest
            ruby: '3.1'
            target: x86_64-unknown-linux-gnu
            zig: false
            run-tests: true
            lib-file: lib/lib-ruby-parser/native/x86_64-unknown-linux-gnu/3.1/lib_ruby_parser.so

          - os: ubuntu-latest
            ruby: '3.0'
            target: x86_64-unknown-linux-gnu
            zig: false
            run-tests: true
            lib-file: lib/lib-ruby-parser/native/x86_64-unknown-linux-gnu/3.0/lib_ruby_parser.so

          - os: macos-latest
            ruby: '3.2'
            target: x86_64-apple-darwin
            zig: false
            run-tests: true
            lib-file: lib/lib-ruby-parser/native/x86_64-apple-darwin/3.2/lib_ruby_parser.bundle

          - os: macos-latest
            ruby: '3.1'
            target: x86_64-apple-darwin
            zig: false
            run-tests: true
            lib-file: lib/lib-ruby-parser/native/x86_64-apple-darwin/3.1/lib_ruby_parser.bundle

          - os: macos-latest
            ruby: '3.0'
            target: x86_64-apple-darwin
            zig: false
            run-tests: true
            lib-file: lib/lib-ruby-parser/native/x86_64-apple-darwin/3.0/lib_ruby_parser.bundle

          - os: macos-latest
            ruby: '3.2'
            target: aarch64-apple-darwin
            zig: true
            run-tests: false
            lib-file: lib/lib-ruby-parser/native/aarch64-apple-darwin/3.2/lib_ruby_parser.bundle

          - os: macos-latest
            ruby: '3.1'
            target: aarch64-apple-darwin
            zig: true
            run-tests: false
            lib-file: lib/lib-ruby-parser/native/aarch64-apple-darwin/3.1/lib_ruby_parser.bundle

          - os: macos-latest
            ruby: '3.0'
            target: aarch64-apple-darwin
            zig: true
            run-tests: false
            lib-file: lib/lib-ruby-parser/native/aarch64-apple-darwin/3.0/lib_ruby_parser.bundle

          - os: windows-latest
            ruby: '3.2'
            target: x86_64-pc-windows-gnu
            zig: false
            run-tests: true
            lib-file: lib/lib-ruby-parser/native/x86_64-pc-windows-gnu/3.2/lib_ruby_parser.so

          - os: windows-latest
            ruby: '3.1'
            target: x86_64-pc-windows-gnu
            zig: false
            run-tests: true
            lib-file: lib/lib-ruby-parser/native/x86_64-pc-windows-gnu/3.1/lib_ruby_parser.so

          - os: windows-latest
            ruby: '3.0'
            target: x86_64-pc-windows-gnu
            zig: false
            run-tests: true
            lib-file: lib/lib-ruby-parser/native/x86_64-pc-windows-gnu/3.0/lib_ruby_parser.so

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.build.ruby }}
          bundler-cache: true

      - name: install zig
        uses: goto-bus-stop/setup-zig@v2
        if: ${{ matrix.build.zig }}

      - name: compile
        run: make dylib

      - name: test
        if: ${{ matrix.build.run-tests }}
        run: make test

      - name: rename dylib
        run: mv ${{ matrix.build.lib-file }} ${{ matrix.build.target }}-${{ matrix.build.ruby }}.dylib

      - name: upload dylib
        uses: actions/upload-artifact@v2
        with:
          path: ${{ matrix.build.target }}-${{ matrix.build.ruby }}.dylib
          name: ${{ matrix.build.target }}-${{ matrix.build.ruby }}.dylib

  build-gem:
    needs: ['compile-and-test']
    name: build per-platform gems
    runs-on: ubuntu-latest
    env:
      TARGET: ${{ matrix.build.target }}
    strategy:
      fail-fast: false
      matrix:
        build:
          - target: x86_64-unknown-linux-gnu
          - target: x86_64-apple-darwin
          - target: aarch64-apple-darwin
          - target: x86_64-pc-windows-gnu

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: download all dylib artifacts
        uses: actions/download-artifact@v2
        with:
          path: '.'

      - name: put all artifacts back to their directories
        run: |
          find .

          mv x86_64-unknown-linux-gnu-3.2.dylib/x86_64-unknown-linux-gnu-3.2.dylib lib/lib-ruby-parser/native/x86_64-unknown-linux-gnu/3.2/lib_ruby_parser.so
          mv x86_64-unknown-linux-gnu-3.1.dylib/x86_64-unknown-linux-gnu-3.1.dylib lib/lib-ruby-parser/native/x86_64-unknown-linux-gnu/3.1/lib_ruby_parser.so
          mv x86_64-unknown-linux-gnu-3.0.dylib/x86_64-unknown-linux-gnu-3.0.dylib lib/lib-ruby-parser/native/x86_64-unknown-linux-gnu/3.0/lib_ruby_parser.so

          mv x86_64-apple-darwin-3.2.dylib/x86_64-apple-darwin-3.2.dylib lib/lib-ruby-parser/native/x86_64-apple-darwin/3.2/lib_ruby_parser.bundle
          mv x86_64-apple-darwin-3.1.dylib/x86_64-apple-darwin-3.1.dylib lib/lib-ruby-parser/native/x86_64-apple-darwin/3.1/lib_ruby_parser.bundle
          mv x86_64-apple-darwin-3.0.dylib/x86_64-apple-darwin-3.0.dylib lib/lib-ruby-parser/native/x86_64-apple-darwin/3.0/lib_ruby_parser.bundle

          mv aarch64-apple-darwin-3.2.dylib/aarch64-apple-darwin-3.2.dylib lib/lib-ruby-parser/native/aarch64-apple-darwin/3.2/lib_ruby_parser.bundle
          mv aarch64-apple-darwin-3.1.dylib/aarch64-apple-darwin-3.1.dylib lib/lib-ruby-parser/native/aarch64-apple-darwin/3.1/lib_ruby_parser.bundle
          mv aarch64-apple-darwin-3.0.dylib/aarch64-apple-darwin-3.0.dylib lib/lib-ruby-parser/native/aarch64-apple-darwin/3.0/lib_ruby_parser.bundle

          mv x86_64-pc-windows-gnu-3.2.dylib/x86_64-pc-windows-gnu-3.2.dylib lib/lib-ruby-parser/native/x86_64-pc-windows-gnu/3.2/lib_ruby_parser.so
          mv x86_64-pc-windows-gnu-3.1.dylib/x86_64-pc-windows-gnu-3.1.dylib lib/lib-ruby-parser/native/x86_64-pc-windows-gnu/3.1/lib_ruby_parser.so
          mv x86_64-pc-windows-gnu-3.0.dylib/x86_64-pc-windows-gnu-3.0.dylib lib/lib-ruby-parser/native/x86_64-pc-windows-gnu/3.0/lib_ruby_parser.so

      - name: run codegen
        run: TARGET=x86_64-unknown-linux-gnu make do-codegen

      - name: pack .gem file
        run: make build-package

      - name: upload .gem file
        uses: actions/upload-artifact@v2
        with:
          path: build/lib-ruby-parser.gem
          name: ${{ matrix.build.target }}-gem

  test-gem:
    needs: ['build-gem']
    name: test per-platform gems
    runs-on: ${{ matrix.build.os }}
    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.1', '3.2', '3.2']
        build:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu

          - os: macos-latest
            target: x86_64-apple-darwin

          - os: windows-latest
            target: x86_64-pc-windows-gnu
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: download .gem artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.build.target }}-gem
          path: gem-artifact

      - name: install gem
        run: gem install gem-artifact/lib-ruby-parser.gem

      - name: run smoke test
        run: ruby -rlib-ruby-parser -e "pp LibRubyParser.parse('42', {})"

  publish-gems:
    needs: ['test-gem']
    name: publish all gems
    runs-on: ubuntu-latest
    env:
      GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_API_TOKEN }}
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: download linux .gem artifact
        uses: actions/download-artifact@v2
        with:
          name: x86_64-unknown-linux-gnu-gem
          path: x86_64-unknown-linux-gnu-gem

      - name: download mac x86 .gem artifact
        uses: actions/download-artifact@v2
        with:
          name: x86_64-apple-darwin-gem
          path: x86_64-apple-darwin-gem

      - name: download mac aarch64 .gem artifact
        uses: actions/download-artifact@v2
        with:
          name: aarch64-apple-darwin-gem
          path: aarch64-apple-darwin-gem

      - name: download windows .gem artifact
        uses: actions/download-artifact@v2
        with:
          name: x86_64-pc-windows-gnu-gem
          path: x86_64-pc-windows-gnu-gem

      - name: push gems
        run: |
          gem push x86_64-unknown-linux-gnu-gem/lib-ruby-parser.gem
          gem push aarch64-apple-darwin-gem/lib-ruby-parser.gem
          gem push x86_64-apple-darwin-gem/lib-ruby-parser.gem
          gem push x86_64-pc-windows-gnu-gem/lib-ruby-parser.gem
